### ISSUE TITLE
Device tracker automation

### ISSUE THREAD

**Issue by Diegoloex** [uvjim/linksys_velop#128]
Would it be too much to ask for a simple example of a notification automation for new connected device? Failing that, with the trigger section it would be worth it. XD

**Comment by uvjim** [comment]
Do you mean when a device comes online or when a brand new device is connected to the mesh, i.e. it's never been on the mesh before?

**Comment by Diegoloex** [comment]
Just the latter, when a new device connects to the mesh. Right now I have it like this, but it stopped working:

trigger:
  - platform: event
    event_type: device_tracker_new_device
    event_data: {}
condition: []
action:
  - service: notify.diego
    data:
      title: Alerta
      message: >-
        Nuevo dispoitivo con: {{"\n"}} {{"\n"}} nombre *{{
        trigger.event.data.host_name }}* {{"\n"}} MAC {{ trigger.event.data.mac
        }} {{"\n"}} IP {{ trigger.event.data.ip }} {{"\n"}} {{"\n"}} Se ha
        conectado a tu Red.
initial_state: true
mode: single

**Comment by uvjim** [comment]
Device trackers are typically used for presence detection (home/away) so that probably won't give you what you're looking for.

The integration doesn't really expose details about devices (apart from as extra attributes) because they could be moving around the mesh.

However, I have been thinking about a way to represent more device level information, such as parental control times (those are currently exposed as attributes of the parental control switch).  I could look at doing a comparison before updates and then emit an event. I'll add it to the list to look at.

**Comment by Diegoloex** [comment]
Lo he tenido funcionando y dándome nombre, ip y Mac de los dispositivos nuevos conectados con esta integración:


![Screenshot_20220309-114138_Home Assistant.jpg](https://user-images.githubusercontent.com/76601842/157426543-7dac1ab3-cbd3-4681-a0f8-7af68ca0129b.jpg)


In case it helps you in your research. Once again, thank you very much indeed.

**Comment by uvjim** [comment]
Device trackers should be configured using the `Configure` option of the integration.

From there you can select the devices you'd like to track and their status will be reported.

The integration hasn't been designed to read anything in from YAML.

**Comment by Diegoloex** [comment]
Mmmmm..... You'll have to forgive me, I don't have much idea of ​​programming and... Well, of nothing computer science, really. So I don't really know how it did it and I don't know why it stopped working either. I'll check to see if I find anything weird...
