### ISSUE TITLE
Discovery finding mesh that is already set up

### ISSUE THREAD

**Issue by HandyHat** [uvjim/linksys_velop#164]
Hey there, thanks for your all your work!

I set up the integration and it's been working great. Recently I swapped out and upgraded my parent node - as I kept the same IP address and local password, the previously set up integration continued to work fine.

![Screenshot_20220411-133334~2.png](https://user-images.githubusercontent.com/58530748/162763678-f93071c5-bbdc-4042-a69a-faff20483fe5.png)

However since then it has also appeared as if it's been newly discovered

![Screenshot_20220411-133321~2.png](https://user-images.githubusercontent.com/58530748/162763866-bf39d1b4-aa5e-4e9b-b924-7365732ec16b.png)

Of course this is a minor issue as the discovered entry can just be ignored. Thanks!

**Comment by uvjim** [comment]
Hmmm... you'll be slightly out of kilter.  The serial number of the parent node is used as the unique_id for the integration.  As you've swapped your parent node out that serial number no longer matches up with the one identified by the original integration.  That explains why you're seeing it again.  This behaviour would have been introduced when multiple integration instances were allowed.

Now, the information will be correct because the IP address is the same so the information can still update because it is still getting valid responses.  However, it's possible that you might be missing additional information until either next reload of the integration or restart of HASS.

I've been wondering for a while about what to do when there's a mismatch between parent nodes.  So far, I've left it to the user to remove the integration and re-add it.  This shouldn't cause any issues in entity_ids in automations etc as they'll be recreated with the same names (unless you've changed the entity_ids manually).
