### ISSUE TITLE
Reboot Control not available on Primary Router

### ISSUE THREAD

**Issue by ddyeakley** [uvjim/linksys_velop#238]
I have 2 Linksys MR9000s, one configured as Primary/Master and one as Bridge/Secondary.   The Reboot Control is available on the Bridge/Secondary but not the Primary.   Any thought on what might cause this?

[config_entry-linksys_velop-0a4694e52b4b547b3072eb72e304cabf.json (1).txt](https://github.com/uvjim/linksys_velop/files/9269913/config_entry-linksys_velop-0a4694e52b4b547b3072eb72e304cabf.json.1.txt)
.

**Comment by uvjim** [comment]
It's by design so the primary node doesn't get rebooted by accident. Typically rebooting the primary reboots all nodes.

If you need to reboot the primary node you can use the `linksys_velop.reboot_node` service - see screenshot.

![Screenshot_2022-08-05-16-42-29-68_c3a231c25ed346e59462e84656a70e50.jpg](https://user-images.githubusercontent.com/8431065/183112981-eae6b5cd-079c-441c-bc09-372fcfcbc1bb.jpg)

**Comment by ddyeakley** [comment]
Thank you!
