### ISSUE TITLE
Exception in _async_get_device_info when dispatching 'update_device_tracker'

### ISSUE THREAD

**Issue by dredjohn21** [uvjim/linksys_velop#305]
After running "channel scan" I noticed the following error in the logs and for ~5 minutes the integration didn't have connectivity to my Linksys Velop nodes (the cards showed n/a).  Seemed to self-recover, so not a critical issue IMHO.

```Logger: homeassistant.util.logging
Source: util/logging.py:156 
First occurred: 8:59:55 AM (28 occurrences) 
Last logged: 9:04:15 AM

Exception in _async_get_device_info when dispatching 'update_device_tracker': () Traceback (most recent call last): File "/config/custom_components/linksys_velop/device_tracker.py", line 192, in _async_get_device_info tracker_details: Device = await mesh.async_get_device_from_id( File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 730, in async_get_device_from_id resp = await self._async_gather_details( File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 415, in _async_gather_details responses: List[Tuple[api.Request, api.Response]] = await asyncio.gather( File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 260, in _async_make_request raise err from None File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 258, in _async_make_request req_resp = await req.execute(timeout=self._timeout) File "/usr/local/lib/python3.10/site-packages/pyvelop/jnap.py", line 176, in execute raise MeshTimeoutError from err pyvelop.exceptions.MeshTimeoutError: Timeout Error
Exception in _async_get_device_info when dispatching 'update_device_tracker': () Traceback (most recent call last): File "/config/custom_components/linksys_velop/device_tracker.py", line 192, in _async_get_device_info tracker_details: Device = await mesh.async_get_device_from_id( File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 730, in async_get_device_from_id resp = await self._async_gather_details( File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 415, in _async_gather_details responses: List[Tuple[api.Request, api.Response]] = await asyncio.gather( File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 260, in _async_make_request raise err from None File "/usr/local/lib/python3.10/site-packages/pyvelop/mesh.py", line 258, in _async_make_request req_resp = await req.execute(timeout=self._timeout) File "/usr/local/lib/python3.10/site-packages/pyvelop/jnap.py", line 182, in execute raise MeshConnectionError from None pyvelop.exceptions.MeshConnectionError: Connection Error
```

**Comment by uvjim** [comment]
Oh, I see why I didn't see these in testing now. I didn't have any device trackers in the test environment so wouldn't have seen them.

The default device tracker interval is 10 seconds (so it'll check every 10 seconds to see the state of the device on the Mesh). You had 28 of those messages logged. That's 280 seconds approximately.

That coincides with the Channel Scan happening (from all the testing I did it seems to take about 5 minutes to complete, but queries to the primary node are slower in that time).

This seems to me to be what I'd expect, but I wonder whether I should pause the device tracker polling whilst the scan is happening, or maybe just suppress the errors.

Hmmm...

**Comment by uvjim** [comment]
Right, better management of that is incoming.  The following will now happen: -

When the `device_tracker` status is being checked if a `MeshConnectionError` or `MeshTimeoutError` is received it will check if an intensive action is running.  If one is it will log a single warning.  If one isn't running a warning will be logged each time the error is raised (which is in keeping with the other errors that are found when `device_trackers` are checked).

If neither of those errors is found then everything will run as normal. This may result in a device being marked offline because the action may cause the connection to drop for a period of time which may breach the `consider_home` threshold.  I did just notice that my device was shown as offline even after the scan finished, but checking the Linksys app and web UI showed that the Mesh did think it was offline even though it wasn't - reconnecting the device to the mesh resolved that.

Hopefully that'll help to stop the logs getting flooded.

I'll push another beta in a little while.  If you could test it, that would be great, because I don't get those errors when I run the scan so I had to fake them to do the tests.

**Comment by uvjim** [comment]
#306 should address this

**Comment by dredjohn21** [comment]
That solved the error logging issues - works perfectly now - thank you sooooo much!
