### ISSUE TITLE
Non funziona

### ISSUE THREAD

**Issue by PaulusThe1** [uvjim/linksys_velop#510]
Purtroppo, anche installando la nuova release 2024.11.2, l'integrazione continua a non funzionare. Il messaggio di errore è sempre lo stesso: "Configurazione non riuscita"

**Comment by uvjim** [comment]
Have you got debug logs and diagnostics please?

**Comment by PaulusThe1** [comment]
[home-assistant_linksys_velop_2024-11-12T13-25-08.452Z.log](https://github.com/user-attachments/files/17717254/home-assistant_linksys_velop_2024-11-12T13-25-08.452Z.log)

**Comment by uvjim** [comment]
Thanks.  There is a timeout issue, but it's difficult to work out what is happening because you also have a huge number of errors in there from other integrations - mostly around them not being found or credentials being bad.

Problem integrations seem to be: -

- bosch
- ingv_centro_nazionale_terremoti
- coronavirus

Your templates (which I'm assuming you are using for the frontend) because you're not checking for states in the recommended way with.  See this for help with the Jinja templates: https://www.home-assistant.io/docs/configuration/templating/#states

As I say, there is a timeout issue, but because of all the other issues, I can't work out whether your network is genuinely not able to respond or if there is actually a problem.

**Comment by PaulusThe1** [comment]
Every integration work properly, without problem. Only Linksys don't function.

Bosch integration is now up (before, its server was down)
ingv work properly
coronavirus will be disinstalled.
Do you want a new log?

**Comment by uvjim** [comment]
I will need a log. You're currently the only person reporting this, and the other issue.

Could you please include the diagnostics file as well?

Could you also confirm what the timeout is set to please.

**Comment by PaulusThe1** [comment]
Hi. I have uninstalled Linksys integration e reinstalled. Now it seems to work. I have added only few device to trace.
I'll let it work like this and then I'll notify you.
Thanks so much for your support.

**Comment by PaulusThe1** [comment]
Scusami, ma ancora non funziona. Adesso non da più l'errore di configurazione, ma non vede nessun device. I nodi mesh li vedo, così come vede tutti i device, ma sono tutti "not home"

**Comment by uvjim** [comment]
I'll close this one as you're now back to the same state you were before.
